FROM node:10
RUN apt-get update -y
RUN apt-get install -y \
  build-essential \
  curl \
  libssl-dev \
  libicu-dev \
  cmake \
  pkg-config \
  imagemagick \
  psmisc \
  vim \
  cron
RUN unlink /etc/localtime
RUN ln -s /usr/share/zoneinfo/Japan /etc/localtime
RUN yarn global add gulp
ENV LANG C.UTF-8
RUN mkdir -p /app
WORKDIR /app
